parameters:
#    school_hello.example.class: School\HelloBundle\Example

services:
#    school_hello.example:
#        class: %school_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
